/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "device_headers/stm32f446xx.h"
#include "device_drivers/rcc_clock.h"

void delay(volatile unsigned int t)
{
    while(t--);
}

int main(void)
{
    /* Enable GPIOA clock */
    CLOCK_Enable(CLK_GPIOA);

    /* Set PA5 as output (MODER5 = 01) */
    GPIOA->MODER &= ~(3 << (5 * 2));
    GPIOA->MODER |=  (1 << (5 * 2));

    while(1)
    {
        /* Toggle PA5 */
        GPIOA->ODR ^= (1 << 5);

        delay(1000000);
    }
}
